# Generated by Django 6.0.6 on 2026-06-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_experience_job_published_at_job_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='content',
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default=' ', max_length=1000),
        ),
    ]
